//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigiChamps.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DigiChampsEntities : DbContext
    {
        public DigiChampsEntities()
            : base("name=DigiChampsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_DC_Ticket_Assign> tbl_DC_Ticket_Assign { get; set; }
        public virtual DbSet<tbl_DC_Aboutus> tbl_DC_Aboutus { get; set; }
        public virtual DbSet<tbl_DC_Attendance> tbl_DC_Attendance { get; set; }
        public virtual DbSet<tbl_DC_Bank_Details> tbl_DC_Bank_Details { get; set; }
        public virtual DbSet<tbl_DC_Banner> tbl_DC_Banner { get; set; }
        public virtual DbSet<tbl_DC_Batch> tbl_DC_Batch { get; set; }
        public virtual DbSet<tbl_DC_Batch_Assign> tbl_DC_Batch_Assign { get; set; }
        public virtual DbSet<tbl_DC_Board> tbl_DC_Board { get; set; }
        public virtual DbSet<tbl_DC_Career> tbl_DC_Career { get; set; }
        public virtual DbSet<tbl_DC_Cart> tbl_DC_Cart { get; set; }
        public virtual DbSet<tbl_DC_Cart_Dtl> tbl_DC_Cart_Dtl { get; set; }
        public virtual DbSet<tbl_DC_Centre> tbl_DC_Centre { get; set; }
        public virtual DbSet<tbl_DC_Chapter> tbl_DC_Chapter { get; set; }
        public virtual DbSet<tbl_DC_City> tbl_DC_City { get; set; }
        public virtual DbSet<tbl_DC_Class> tbl_DC_Class { get; set; }
        public virtual DbSet<tbl_DC_CouponCode> tbl_DC_CouponCode { get; set; }
        public virtual DbSet<tbl_DC_CouponType> tbl_DC_CouponType { get; set; }
        public virtual DbSet<tbl_DC_Course_Teacher_Assign> tbl_DC_Course_Teacher_Assign { get; set; }
        public virtual DbSet<tbl_DC_Exam> tbl_DC_Exam { get; set; }
        public virtual DbSet<tbl_DC_Exam_Power> tbl_DC_Exam_Power { get; set; }
        public virtual DbSet<tbl_DC_Exam_Result> tbl_DC_Exam_Result { get; set; }
        public virtual DbSet<tbl_DC_Exam_Result_Dtl> tbl_DC_Exam_Result_Dtl { get; set; }
        public virtual DbSet<tbl_DC_Exam_Type> tbl_DC_Exam_Type { get; set; }
        public virtual DbSet<tbl_DC_FAQs> tbl_DC_FAQs { get; set; }
        public virtual DbSet<tbl_DC_Feedback> tbl_DC_Feedback { get; set; }
        public virtual DbSet<tbl_DC_Feedback_Chapter> tbl_DC_Feedback_Chapter { get; set; }
        public virtual DbSet<tbl_DC_Feedback_Teacher> tbl_DC_Feedback_Teacher { get; set; }
        public virtual DbSet<tbl_DC_LoginStatus> tbl_DC_LoginStatus { get; set; }
        public virtual DbSet<tbl_DC_MailConfigBody> tbl_DC_MailConfigBody { get; set; }
        public virtual DbSet<tbl_DC_MailType> tbl_DC_MailType { get; set; }
        public virtual DbSet<tbl_DC_Marketing_Blog> tbl_DC_Marketing_Blog { get; set; }
        public virtual DbSet<tbl_DC_Menu_Permission> tbl_DC_Menu_Permission { get; set; }
        public virtual DbSet<tbl_DC_Menuitems> tbl_DC_Menuitems { get; set; }
        public virtual DbSet<tbl_DC_Module> tbl_DC_Module { get; set; }
        public virtual DbSet<tbl_DC_Notification> tbl_DC_Notification { get; set; }
        public virtual DbSet<tbl_DC_Order> tbl_DC_Order { get; set; }
        public virtual DbSet<tbl_DC_Order_Pkg> tbl_DC_Order_Pkg { get; set; }
        public virtual DbSet<tbl_DC_Order_Pkg_Sub> tbl_DC_Order_Pkg_Sub { get; set; }
        public virtual DbSet<tbl_DC_Order_Pkg_Sub_Mod> tbl_DC_Order_Pkg_Sub_Mod { get; set; }
        public virtual DbSet<tbl_DC_Order_Tax> tbl_DC_Order_Tax { get; set; }
        public virtual DbSet<tbl_DC_OTP> tbl_DC_OTP { get; set; }
        public virtual DbSet<tbl_DC_Our_Team> tbl_DC_Our_Team { get; set; }
        public virtual DbSet<tbl_DC_Package> tbl_DC_Package { get; set; }
        public virtual DbSet<tbl_DC_Package_Dtl> tbl_DC_Package_Dtl { get; set; }
        public virtual DbSet<tbl_DC_Package_Period> tbl_DC_Package_Period { get; set; }
        public virtual DbSet<tbl_DC_PackageSub_Dtl> tbl_DC_PackageSub_Dtl { get; set; }
        public virtual DbSet<tbl_DC_Percentage> tbl_DC_Percentage { get; set; }
        public virtual DbSet<tbl_DC_Power_Question> tbl_DC_Power_Question { get; set; }
        public virtual DbSet<tbl_DC_Pre_book> tbl_DC_Pre_book { get; set; }
        public virtual DbSet<tbl_DC_Prefix> tbl_DC_Prefix { get; set; }
        public virtual DbSet<tbl_DC_PrefixType> tbl_DC_PrefixType { get; set; }
        public virtual DbSet<tbl_DC_Question> tbl_DC_Question { get; set; }
        public virtual DbSet<tbl_DC_Question_Answer> tbl_DC_Question_Answer { get; set; }
        public virtual DbSet<tbl_DC_Question_Images> tbl_DC_Question_Images { get; set; }
        public virtual DbSet<tbl_DC_Registration> tbl_DC_Registration { get; set; }
        public virtual DbSet<tbl_DC_Registration_Dtl> tbl_DC_Registration_Dtl { get; set; }
        public virtual DbSet<tbl_DC_Role> tbl_DC_Role { get; set; }
        public virtual DbSet<tbl_DC_Role_Type> tbl_DC_Role_Type { get; set; }
        public virtual DbSet<tbl_DC_Sample_Image> tbl_DC_Sample_Image { get; set; }
        public virtual DbSet<tbl_DC_Security_Question> tbl_DC_Security_Question { get; set; }
        public virtual DbSet<tbl_DC_Shift_Mst> tbl_DC_Shift_Mst { get; set; }
        public virtual DbSet<tbl_DC_Shift_Teacher_Assign> tbl_DC_Shift_Teacher_Assign { get; set; }
        public virtual DbSet<tbl_DC_Sms_API> tbl_DC_Sms_API { get; set; }
        public virtual DbSet<tbl_DC_Sms_Template> tbl_DC_Sms_Template { get; set; }
        public virtual DbSet<tbl_DC_Smtp_Details> tbl_DC_Smtp_Details { get; set; }
        public virtual DbSet<tbl_DC_State> tbl_DC_State { get; set; }
        public virtual DbSet<tbl_DC_Student_Batch_Assign> tbl_DC_Student_Batch_Assign { get; set; }
        public virtual DbSet<tbl_DC_Subject> tbl_DC_Subject { get; set; }
        public virtual DbSet<tbl_DC_Tablet_Image> tbl_DC_Tablet_Image { get; set; }
        public virtual DbSet<tbl_DC_Tablet_Pkg_Dtl> tbl_DC_Tablet_Pkg_Dtl { get; set; }
        public virtual DbSet<tbl_DC_Tablet_Purchase> tbl_DC_Tablet_Purchase { get; set; }
        public virtual DbSet<tbl_DC_Tablet_Technical_Details> tbl_DC_Tablet_Technical_Details { get; set; }
        public virtual DbSet<tbl_DC_Tax_Master> tbl_DC_Tax_Master { get; set; }
        public virtual DbSet<tbl_DC_Tax_Type_Master> tbl_DC_Tax_Type_Master { get; set; }
        public virtual DbSet<tbl_DC_Teacher> tbl_DC_Teacher { get; set; }
        public virtual DbSet<tbl_DC_Test_Assign> tbl_DC_Test_Assign { get; set; }
        public virtual DbSet<tbl_DC_Ticket> tbl_DC_Ticket { get; set; }
        public virtual DbSet<tbl_DC_Ticket_Dtl> tbl_DC_Ticket_Dtl { get; set; }
        public virtual DbSet<tbl_DC_Ticket_Thread> tbl_DC_Ticket_Thread { get; set; }
        public virtual DbSet<tbl_DC_Topic> tbl_DC_Topic { get; set; }
        public virtual DbSet<tbl_DC_Topic_Report> tbl_DC_Topic_Report { get; set; }
        public virtual DbSet<tbl_DC_USER_MASTER> tbl_DC_USER_MASTER { get; set; }
        public virtual DbSet<tbl_DC_USER_SECURITY> tbl_DC_USER_SECURITY { get; set; }
        public virtual DbSet<tbl_DC_Video_Backup> tbl_DC_Video_Backup { get; set; }
        public virtual DbSet<View_All_Student_Details> View_All_Student_Details { get; set; }
        public virtual DbSet<View_Course_Teacher_Assign> View_Course_Teacher_Assign { get; set; }
        public virtual DbSet<View_DC_All_Tickets_Details> View_DC_All_Tickets_Details { get; set; }
        public virtual DbSet<View_DC_CourseAssign> View_DC_CourseAssign { get; set; }
        public virtual DbSet<View_DC_Exam_Setup> View_DC_Exam_Setup { get; set; }
        public virtual DbSet<View_DC_Order_Details> View_DC_Order_Details { get; set; }
        public virtual DbSet<View_DC_Package> View_DC_Package { get; set; }
        public virtual DbSet<View_DC_SMS_API> View_DC_SMS_API { get; set; }
        public virtual DbSet<View_DC_Student_details> View_DC_Student_details { get; set; }
        public virtual DbSet<View_DC_Teacher_Shift> View_DC_Teacher_Shift { get; set; }
        public virtual DbSet<View_DC_Tickets_and_Teacher> View_DC_Tickets_and_Teacher { get; set; }
        public virtual DbSet<Vw_Attendance_Report> Vw_Attendance_Report { get; set; }
        public virtual DbSet<VW_DC_Assign_Batch> VW_DC_Assign_Batch { get; set; }
        public virtual DbSet<VW_DC_Attendance_Batch_Details> VW_DC_Attendance_Batch_Details { get; set; }
        public virtual DbSet<VW_DC_Package_Learn> VW_DC_Package_Learn { get; set; }
        public virtual DbSet<VW_DC_Package_Learn_Module> VW_DC_Package_Learn_Module { get; set; }
        public virtual DbSet<VW_DC_Role> VW_DC_Role { get; set; }
        public virtual DbSet<VW_Offline_Student_Orders> VW_Offline_Student_Orders { get; set; }
        public virtual DbSet<VW_Prebook_Students> VW_Prebook_Students { get; set; }
        public virtual DbSet<tbl_DC_School_Info> tbl_DC_School_Info { get; set; }
        public virtual DbSet<tbl_DC_SchoolUser> tbl_DC_SchoolUser { get; set; }
        public virtual DbSet<tbl_DC_Class_Section> tbl_DC_Class_Section { get; set; }
        public virtual DbSet<tbl_DC_School_Class> tbl_DC_School_Class { get; set; }
        public virtual DbSet<tbl_DC_School_Subject> tbl_DC_School_Subject { get; set; }
        public virtual DbSet<tbl_DC_ToppersWay> tbl_DC_ToppersWay { get; set; }
        public virtual DbSet<tbl_DC_School_AssingTeacher> tbl_DC_School_AssingTeacher { get; set; }
        public virtual DbSet<tbl_DC_School_ExamSchedule> tbl_DC_School_ExamSchedule { get; set; }
        public virtual DbSet<tbl_DC_School_ExamType> tbl_DC_School_ExamType { get; set; }
        public virtual DbSet<tbl_DC_School_StudyMaterial> tbl_DC_School_StudyMaterial { get; set; }
        public virtual DbSet<tbl_DC_School_MessageCreation> tbl_DC_School_MessageCreation { get; set; }
        public virtual DbSet<tbl_DC_Period> tbl_DC_Period { get; set; }
        public virtual DbSet<tbl_DC_Shool_TimeTable> tbl_DC_Shool_TimeTable { get; set; }
        public virtual DbSet<tbl_DC_School_Homework> tbl_DC_School_Homework { get; set; }
    
        public virtual int login_fin_status(Nullable<int> sessionid)
        {
            var sessionidParameter = sessionid.HasValue ?
                new ObjectParameter("sessionid", sessionid) :
                new ObjectParameter("sessionid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("login_fin_status", sessionidParameter);
        }
    
        public virtual ObjectResult<Order_report_Result> Order_report()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Order_report_Result>("Order_report");
        }
    
        public virtual ObjectResult<SP_chapterList_Result> SP_chapterList(string ids)
        {
            var idsParameter = ids != null ?
                new ObjectParameter("ids", ids) :
                new ObjectParameter("ids", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_chapterList_Result>("SP_chapterList", idsParameter);
        }
    
        public virtual ObjectResult<SP_count_of_power_Result> SP_count_of_power(Nullable<int> ch_id, Nullable<int> eaxam_id)
        {
            var ch_idParameter = ch_id.HasValue ?
                new ObjectParameter("ch_id", ch_id) :
                new ObjectParameter("ch_id", typeof(int));
    
            var eaxam_idParameter = eaxam_id.HasValue ?
                new ObjectParameter("eaxam_id", eaxam_id) :
                new ObjectParameter("eaxam_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_count_of_power_Result>("SP_count_of_power", ch_idParameter, eaxam_idParameter);
        }
    
        public virtual ObjectResult<SP_count_of_power_sub_Result> SP_count_of_power_sub(Nullable<int> sb_id, Nullable<int> exam_typ)
        {
            var sb_idParameter = sb_id.HasValue ?
                new ObjectParameter("sb_id", sb_id) :
                new ObjectParameter("sb_id", typeof(int));
    
            var exam_typParameter = exam_typ.HasValue ?
                new ObjectParameter("exam_typ", exam_typ) :
                new ObjectParameter("exam_typ", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_count_of_power_sub_Result>("SP_count_of_power_sub", sb_idParameter, exam_typParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SP_count_of_questions(Nullable<int> ch_id, Nullable<int> eaxam_id)
        {
            var ch_idParameter = ch_id.HasValue ?
                new ObjectParameter("ch_id", ch_id) :
                new ObjectParameter("ch_id", typeof(int));
    
            var eaxam_idParameter = eaxam_id.HasValue ?
                new ObjectParameter("eaxam_id", eaxam_id) :
                new ObjectParameter("eaxam_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_count_of_questions", ch_idParameter, eaxam_idParameter);
        }
    
        public virtual ObjectResult<SP_DC_Askdoubt_Board_Result> SP_DC_Askdoubt_Board(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_DC_Askdoubt_Board_Result>("SP_DC_Askdoubt_Board", idParameter);
        }
    
        public virtual ObjectResult<SP_DC_Askdoubt_Chapter_Result> SP_DC_Askdoubt_Chapter(Nullable<int> id, Nullable<int> bid, Nullable<int> cid, Nullable<int> sid)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var bidParameter = bid.HasValue ?
                new ObjectParameter("bid", bid) :
                new ObjectParameter("bid", typeof(int));
    
            var cidParameter = cid.HasValue ?
                new ObjectParameter("cid", cid) :
                new ObjectParameter("cid", typeof(int));
    
            var sidParameter = sid.HasValue ?
                new ObjectParameter("sid", sid) :
                new ObjectParameter("sid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_DC_Askdoubt_Chapter_Result>("SP_DC_Askdoubt_Chapter", idParameter, bidParameter, cidParameter, sidParameter);
        }
    
        public virtual ObjectResult<SP_DC_Askdoubt_Class_Result> SP_DC_Askdoubt_Class(Nullable<int> id, Nullable<int> bid)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var bidParameter = bid.HasValue ?
                new ObjectParameter("bid", bid) :
                new ObjectParameter("bid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_DC_Askdoubt_Class_Result>("SP_DC_Askdoubt_Class", idParameter, bidParameter);
        }
    
        public virtual ObjectResult<SP_DC_Askdoubt_Subject_Result> SP_DC_Askdoubt_Subject(Nullable<int> id, Nullable<int> bid, Nullable<int> cid)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var bidParameter = bid.HasValue ?
                new ObjectParameter("bid", bid) :
                new ObjectParameter("bid", typeof(int));
    
            var cidParameter = cid.HasValue ?
                new ObjectParameter("cid", cid) :
                new ObjectParameter("cid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_DC_Askdoubt_Subject_Result>("SP_DC_Askdoubt_Subject", idParameter, bidParameter, cidParameter);
        }
    
        public virtual ObjectResult<SP_DC_Assign_Batch_Details_Result> SP_DC_Assign_Batch_Details()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_DC_Assign_Batch_Details_Result>("SP_DC_Assign_Batch_Details");
        }
    
        public virtual ObjectResult<SP_DC_COunt_Student_Tickets_Result> SP_DC_COunt_Student_Tickets(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_DC_COunt_Student_Tickets_Result>("SP_DC_COunt_Student_Tickets", idParameter);
        }
    
        public virtual int SP_DC_EMAIL_NOTIFICATION()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DC_EMAIL_NOTIFICATION");
        }
    
        public virtual ObjectResult<SP_DC_Examresultcalulation_Result> SP_DC_Examresultcalulation(Nullable<int> sid, Nullable<int> rid)
        {
            var sidParameter = sid.HasValue ?
                new ObjectParameter("sid", sid) :
                new ObjectParameter("sid", typeof(int));
    
            var ridParameter = rid.HasValue ?
                new ObjectParameter("rid", rid) :
                new ObjectParameter("rid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_DC_Examresultcalulation_Result>("SP_DC_Examresultcalulation", sidParameter, ridParameter);
        }
    
        public virtual ObjectResult<SP_DC_feedback_Result> SP_DC_feedback()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_DC_feedback_Result>("SP_DC_feedback");
        }
    
        public virtual ObjectResult<SP_DC_Feedback_Chapter_Result> SP_DC_Feedback_Chapter(Nullable<int> redgid)
        {
            var redgidParameter = redgid.HasValue ?
                new ObjectParameter("redgid", redgid) :
                new ObjectParameter("redgid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_DC_Feedback_Chapter_Result>("SP_DC_Feedback_Chapter", redgidParameter);
        }
    
        public virtual ObjectResult<SP_DC_Feedback_Teacher_Result> SP_DC_Feedback_Teacher(Nullable<int> redgid)
        {
            var redgidParameter = redgid.HasValue ?
                new ObjectParameter("redgid", redgid) :
                new ObjectParameter("redgid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_DC_Feedback_Teacher_Result>("SP_DC_Feedback_Teacher", redgidParameter);
        }
    
        public virtual ObjectResult<Sp_DC_Free_Exam_Result> Sp_DC_Free_Exam(Nullable<int> regd_id)
        {
            var regd_idParameter = regd_id.HasValue ?
                new ObjectParameter("regd_id", regd_id) :
                new ObjectParameter("regd_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_DC_Free_Exam_Result>("Sp_DC_Free_Exam", regd_idParameter);
        }
    
        public virtual ObjectResult<string> SP_DC_Generate_Ticket_ID()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_DC_Generate_Ticket_ID");
        }
    
        public virtual ObjectResult<SP_DC_Get_maildetails_Result> SP_DC_Get_maildetails(string name)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_DC_Get_maildetails_Result>("SP_DC_Get_maildetails", nameParameter);
        }
    
        public virtual ObjectResult<SP_DC_Get_Power_Result_Result> SP_DC_Get_Power_Result(Nullable<int> result_id)
        {
            var result_idParameter = result_id.HasValue ?
                new ObjectParameter("result_id", result_id) :
                new ObjectParameter("result_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_DC_Get_Power_Result_Result>("SP_DC_Get_Power_Result", result_idParameter);
        }
    
        public virtual ObjectResult<Sp_DC_Getall_Packagelearn_Result> Sp_DC_Getall_Packagelearn(Nullable<int> class_id)
        {
            var class_idParameter = class_id.HasValue ?
                new ObjectParameter("class_id", class_id) :
                new ObjectParameter("class_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_DC_Getall_Packagelearn_Result>("Sp_DC_Getall_Packagelearn", class_idParameter);
        }
    
        public virtual ObjectResult<SP_DC_Getallquestion_Appeard_Result> SP_DC_Getallquestion_Appeard(Nullable<int> rid)
        {
            var ridParameter = rid.HasValue ?
                new ObjectParameter("rid", rid) :
                new ObjectParameter("rid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_DC_Getallquestion_Appeard_Result>("SP_DC_Getallquestion_Appeard", ridParameter);
        }
    
        public virtual ObjectResult<SP_DC_Getchapter_Result> SP_DC_Getchapter(Nullable<int> regdid)
        {
            var regdidParameter = regdid.HasValue ?
                new ObjectParameter("regdid", regdid) :
                new ObjectParameter("regdid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_DC_Getchapter_Result>("SP_DC_Getchapter", regdidParameter);
        }
    
        public virtual ObjectResult<SP_DC_GetExamwisequestions_Result> SP_DC_GetExamwisequestions(Nullable<int> chapterid)
        {
            var chapteridParameter = chapterid.HasValue ?
                new ObjectParameter("chapterid", chapterid) :
                new ObjectParameter("chapterid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_DC_GetExamwisequestions_Result>("SP_DC_GetExamwisequestions", chapteridParameter);
        }
    
        public virtual ObjectResult<SP_DC_GetModules_for_api_Result> SP_DC_GetModules_for_api(Nullable<int> cahpter, Nullable<int> redg_id)
        {
            var cahpterParameter = cahpter.HasValue ?
                new ObjectParameter("cahpter", cahpter) :
                new ObjectParameter("cahpter", typeof(int));
    
            var redg_idParameter = redg_id.HasValue ?
                new ObjectParameter("redg_id", redg_id) :
                new ObjectParameter("redg_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_DC_GetModules_for_api_Result>("SP_DC_GetModules_for_api", cahpterParameter, redg_idParameter);
        }
    
        public virtual ObjectResult<SP_DC_lead_Result> SP_DC_lead(Nullable<int> exam_ID)
        {
            var exam_IDParameter = exam_ID.HasValue ?
                new ObjectParameter("exam_ID", exam_ID) :
                new ObjectParameter("exam_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_DC_lead_Result>("SP_DC_lead", exam_IDParameter);
        }
    
        public virtual ObjectResult<SP_DC_LeaderBoards_Result> SP_DC_LeaderBoards(Nullable<int> subject_id, Nullable<int> chapter_id)
        {
            var subject_idParameter = subject_id.HasValue ?
                new ObjectParameter("subject_id", subject_id) :
                new ObjectParameter("subject_id", typeof(int));
    
            var chapter_idParameter = chapter_id.HasValue ?
                new ObjectParameter("chapter_id", chapter_id) :
                new ObjectParameter("chapter_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_DC_LeaderBoards_Result>("SP_DC_LeaderBoards", subject_idParameter, chapter_idParameter);
        }
    
        public virtual ObjectResult<SP_DC_Offline_exams_Result> SP_DC_Offline_exams(Nullable<int> redgid, Nullable<int> ex_typ)
        {
            var redgidParameter = redgid.HasValue ?
                new ObjectParameter("redgid", redgid) :
                new ObjectParameter("redgid", typeof(int));
    
            var ex_typParameter = ex_typ.HasValue ?
                new ObjectParameter("ex_typ", ex_typ) :
                new ObjectParameter("ex_typ", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_DC_Offline_exams_Result>("SP_DC_Offline_exams", redgidParameter, ex_typParameter);
        }
    
        public virtual ObjectResult<SP_DC_Order_Details_Result> SP_DC_Order_Details(Nullable<int> std)
        {
            var stdParameter = std.HasValue ?
                new ObjectParameter("std", std) :
                new ObjectParameter("std", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_DC_Order_Details_Result>("SP_DC_Order_Details", stdParameter);
        }
    
        public virtual ObjectResult<SP_DC_Parentg1_Result> SP_DC_Parentg1(Nullable<int> parent_id, Nullable<int> exam_typ)
        {
            var parent_idParameter = parent_id.HasValue ?
                new ObjectParameter("parent_id", parent_id) :
                new ObjectParameter("parent_id", typeof(int));
    
            var exam_typParameter = exam_typ.HasValue ?
                new ObjectParameter("exam_typ", exam_typ) :
                new ObjectParameter("exam_typ", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_DC_Parentg1_Result>("SP_DC_Parentg1", parent_idParameter, exam_typParameter);
        }
    
        public virtual ObjectResult<SP_DC_Parentg2_Result> SP_DC_Parentg2(Nullable<int> result_id)
        {
            var result_idParameter = result_id.HasValue ?
                new ObjectParameter("result_id", result_id) :
                new ObjectParameter("result_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_DC_Parentg2_Result>("SP_DC_Parentg2", result_idParameter);
        }
    
        public virtual ObjectResult<SP_DC_Parentg3_Result> SP_DC_Parentg3(Nullable<int> result_id)
        {
            var result_idParameter = result_id.HasValue ?
                new ObjectParameter("result_id", result_id) :
                new ObjectParameter("result_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_DC_Parentg3_Result>("SP_DC_Parentg3", result_idParameter);
        }
    
        public virtual ObjectResult<SP_DC_Power_Examsetup_Result> SP_DC_Power_Examsetup(Nullable<int> examid)
        {
            var examidParameter = examid.HasValue ?
                new ObjectParameter("examid", examid) :
                new ObjectParameter("examid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_DC_Power_Examsetup_Result>("SP_DC_Power_Examsetup", examidParameter);
        }
    
        public virtual ObjectResult<SP_DC_Procedurefor_Retest_Result> SP_DC_Procedurefor_Retest(Nullable<int> exam_id, Nullable<int> redgistration_id)
        {
            var exam_idParameter = exam_id.HasValue ?
                new ObjectParameter("exam_id", exam_id) :
                new ObjectParameter("exam_id", typeof(int));
    
            var redgistration_idParameter = redgistration_id.HasValue ?
                new ObjectParameter("redgistration_id", redgistration_id) :
                new ObjectParameter("redgistration_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_DC_Procedurefor_Retest_Result>("SP_DC_Procedurefor_Retest", exam_idParameter, redgistration_idParameter);
        }
    
        public virtual ObjectResult<SP_DC_Procedurefor_test_Result> SP_DC_Procedurefor_test(Nullable<int> exam_id, Nullable<int> redgistration_id, Nullable<int> exam_typ)
        {
            var exam_idParameter = exam_id.HasValue ?
                new ObjectParameter("exam_id", exam_id) :
                new ObjectParameter("exam_id", typeof(int));
    
            var redgistration_idParameter = redgistration_id.HasValue ?
                new ObjectParameter("redgistration_id", redgistration_id) :
                new ObjectParameter("redgistration_id", typeof(int));
    
            var exam_typParameter = exam_typ.HasValue ?
                new ObjectParameter("exam_typ", exam_typ) :
                new ObjectParameter("exam_typ", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_DC_Procedurefor_test_Result>("SP_DC_Procedurefor_test", exam_idParameter, redgistration_idParameter, exam_typParameter);
        }
    
        public virtual ObjectResult<SP_DC_Question_Count_Result> SP_DC_Question_Count(Nullable<int> std)
        {
            var stdParameter = std.HasValue ?
                new ObjectParameter("std", std) :
                new ObjectParameter("std", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_DC_Question_Count_Result>("SP_DC_Question_Count", stdParameter);
        }
    
        public virtual ObjectResult<SP_DC_Shiftreport_Result> SP_DC_Shiftreport(Nullable<int> tid)
        {
            var tidParameter = tid.HasValue ?
                new ObjectParameter("tid", tid) :
                new ObjectParameter("tid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_DC_Shiftreport_Result>("SP_DC_Shiftreport", tidParameter);
        }
    
        public virtual ObjectResult<SP_DC_Startegic_Report_Result> SP_DC_Startegic_Report(Nullable<int> result_id)
        {
            var result_idParameter = result_id.HasValue ?
                new ObjectParameter("result_id", result_id) :
                new ObjectParameter("result_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_DC_Startegic_Report_Result>("SP_DC_Startegic_Report", result_idParameter);
        }
    
        public virtual ObjectResult<SP_DC_Student_Feedback_Result> SP_DC_Student_Feedback(string val)
        {
            var valParameter = val != null ?
                new ObjectParameter("val", val) :
                new ObjectParameter("val", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_DC_Student_Feedback_Result>("SP_DC_Student_Feedback", valParameter);
        }
    
        public virtual ObjectResult<SP_DC_Student_Feedback_Chap_Result> SP_DC_Student_Feedback_Chap(string val)
        {
            var valParameter = val != null ?
                new ObjectParameter("val", val) :
                new ObjectParameter("val", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_DC_Student_Feedback_Chap_Result>("SP_DC_Student_Feedback_Chap", valParameter);
        }
    
        public virtual ObjectResult<SP_DC_Student_Feedback_Teach_Result> SP_DC_Student_Feedback_Teach(string val)
        {
            var valParameter = val != null ?
                new ObjectParameter("val", val) :
                new ObjectParameter("val", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_DC_Student_Feedback_Teach_Result>("SP_DC_Student_Feedback_Teach", valParameter);
        }
    
        public virtual ObjectResult<SP_DC_Student_PacakgeModule_ID_Result> SP_DC_Student_PacakgeModule_ID(Nullable<int> class_id)
        {
            var class_idParameter = class_id.HasValue ?
                new ObjectParameter("class_id", class_id) :
                new ObjectParameter("class_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_DC_Student_PacakgeModule_ID_Result>("SP_DC_Student_PacakgeModule_ID", class_idParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> SP_DC_Student_Profile_Progress(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("SP_DC_Student_Profile_Progress", idParameter);
        }
    
        public virtual ObjectResult<SP_DC_teacher_All_Batch_Result> SP_DC_teacher_All_Batch(Nullable<int> teacher_id)
        {
            var teacher_idParameter = teacher_id.HasValue ?
                new ObjectParameter("teacher_id", teacher_id) :
                new ObjectParameter("teacher_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_DC_teacher_All_Batch_Result>("SP_DC_teacher_All_Batch", teacher_idParameter);
        }
    
        public virtual ObjectResult<SP_DC_Teacher_Ticket_Count_Result> SP_DC_Teacher_Ticket_Count()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_DC_Teacher_Ticket_Count_Result>("SP_DC_Teacher_Ticket_Count");
        }
    
        public virtual ObjectResult<SP_DC_TES_Result> SP_DC_TES(Nullable<int> qno, Nullable<int> redgid, Nullable<int> exid, Nullable<int> pwid)
        {
            var qnoParameter = qno.HasValue ?
                new ObjectParameter("qno", qno) :
                new ObjectParameter("qno", typeof(int));
    
            var redgidParameter = redgid.HasValue ?
                new ObjectParameter("redgid", redgid) :
                new ObjectParameter("redgid", typeof(int));
    
            var exidParameter = exid.HasValue ?
                new ObjectParameter("exid", exid) :
                new ObjectParameter("exid", typeof(int));
    
            var pwidParameter = pwid.HasValue ?
                new ObjectParameter("pwid", pwid) :
                new ObjectParameter("pwid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_DC_TES_Result>("SP_DC_TES", qnoParameter, redgidParameter, exidParameter, pwidParameter);
        }
    
        public virtual ObjectResult<SP_DC_TestAssign_Result> SP_DC_TestAssign(Nullable<int> exam_type)
        {
            var exam_typeParameter = exam_type.HasValue ?
                new ObjectParameter("Exam_type", exam_type) :
                new ObjectParameter("Exam_type", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_DC_TestAssign_Result>("SP_DC_TestAssign", exam_typeParameter);
        }
    
        public virtual ObjectResult<SP_DC_Ticket_Assigned_to_teacher_Result> SP_DC_Ticket_Assigned_to_teacher(Nullable<int> teacher_id)
        {
            var teacher_idParameter = teacher_id.HasValue ?
                new ObjectParameter("teacher_id", teacher_id) :
                new ObjectParameter("teacher_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_DC_Ticket_Assigned_to_teacher_Result>("SP_DC_Ticket_Assigned_to_teacher", teacher_idParameter);
        }
    
        public virtual ObjectResult<string> SP_DC_Ticket_Similaranswers(string questions)
        {
            var questionsParameter = questions != null ?
                new ObjectParameter("questions", questions) :
                new ObjectParameter("questions", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_DC_Ticket_Similaranswers", questionsParameter);
        }
    
        public virtual ObjectResult<SP_ExamList_Result> SP_ExamList(Nullable<int> ids, Nullable<int> type_id)
        {
            var idsParameter = ids.HasValue ?
                new ObjectParameter("ids", ids) :
                new ObjectParameter("ids", typeof(int));
    
            var type_idParameter = type_id.HasValue ?
                new ObjectParameter("type_id", type_id) :
                new ObjectParameter("type_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ExamList_Result>("SP_ExamList", idsParameter, type_idParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SP_Offline_Exams_Count(string sid, Nullable<int> type_id)
        {
            var sidParameter = sid != null ?
                new ObjectParameter("sid", sid) :
                new ObjectParameter("sid", typeof(string));
    
            var type_idParameter = type_id.HasValue ?
                new ObjectParameter("type_id", type_id) :
                new ObjectParameter("type_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_Offline_Exams_Count", sidParameter, type_idParameter);
        }
    
        public virtual ObjectResult<SP_Order_Datewise_Result> SP_Order_Datewise(Nullable<int> month)
        {
            var monthParameter = month.HasValue ?
                new ObjectParameter("month", month) :
                new ObjectParameter("month", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Order_Datewise_Result>("SP_Order_Datewise", monthParameter);
        }
    
        [DbFunction("DigiChampsEntities", "SplitInts")]
        public virtual IQueryable<Nullable<int>> SplitInts(string list, string delimiter)
        {
            var listParameter = list != null ?
                new ObjectParameter("List", list) :
                new ObjectParameter("List", typeof(string));
    
            var delimiterParameter = delimiter != null ?
                new ObjectParameter("Delimiter", delimiter) :
                new ObjectParameter("Delimiter", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<Nullable<int>>("[DigiChampsEntities].[SplitInts](@List, @Delimiter)", listParameter, delimiterParameter);
        }
    
        [DbFunction("DigiChampsEntities", "SplitString")]
        public virtual IQueryable<string> SplitString(string input, string character)
        {
            var inputParameter = input != null ?
                new ObjectParameter("Input", input) :
                new ObjectParameter("Input", typeof(string));
    
            var characterParameter = character != null ?
                new ObjectParameter("Character", character) :
                new ObjectParameter("Character", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<string>("[DigiChampsEntities].[SplitString](@Input, @Character)", inputParameter, characterParameter);
        }
    
        public virtual int SqlQueryNotificationStoredProcedure_1d3255d4_ca1b_47fc_8ba4_d3c54448945a()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SqlQueryNotificationStoredProcedure_1d3255d4_ca1b_47fc_8ba4_d3c54448945a");
        }
    
        public virtual int SqlQueryNotificationStoredProcedure_9f13a863_cada_4fee_aea9_0d9a8f9a86a8()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SqlQueryNotificationStoredProcedure_9f13a863_cada_4fee_aea9_0d9a8f9a86a8");
        }
    
        public virtual ObjectResult<string> Taxprefix_code()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("Taxprefix_code");
        }
    
        [DbFunction("DigiChampsEntities", "tbl_exam_question_count")]
        public virtual IQueryable<tbl_exam_question_count_Result> tbl_exam_question_count(Nullable<int> examid)
        {
            var examidParameter = examid.HasValue ?
                new ObjectParameter("examid", examid) :
                new ObjectParameter("examid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<tbl_exam_question_count_Result>("[DigiChampsEntities].[tbl_exam_question_count](@examid)", examidParameter);
        }
    
        public virtual ObjectResult<SP_DC_Expiry_Date_Notify_Result> SP_DC_Expiry_Date_Notify(Nullable<int> day)
        {
            var dayParameter = day.HasValue ?
                new ObjectParameter("day", day) :
                new ObjectParameter("day", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_DC_Expiry_Date_Notify_Result>("SP_DC_Expiry_Date_Notify", dayParameter);
        }
    
        public virtual int usp_SchoolAdmin(Nullable<System.Guid> adminId, Nullable<System.Guid> schoolId, string adminFirstname, string adminLastname, string adminEmailAddress, string adminUserId, string adminPassword, string adminProfilePhoto, Nullable<System.DateTime> createdDate, Nullable<System.DateTime> modifiedDate, Nullable<bool> isActive)
        {
            var adminIdParameter = adminId.HasValue ?
                new ObjectParameter("AdminId", adminId) :
                new ObjectParameter("AdminId", typeof(System.Guid));
    
            var schoolIdParameter = schoolId.HasValue ?
                new ObjectParameter("SchoolId", schoolId) :
                new ObjectParameter("SchoolId", typeof(System.Guid));
    
            var adminFirstnameParameter = adminFirstname != null ?
                new ObjectParameter("AdminFirstname", adminFirstname) :
                new ObjectParameter("AdminFirstname", typeof(string));
    
            var adminLastnameParameter = adminLastname != null ?
                new ObjectParameter("AdminLastname", adminLastname) :
                new ObjectParameter("AdminLastname", typeof(string));
    
            var adminEmailAddressParameter = adminEmailAddress != null ?
                new ObjectParameter("AdminEmailAddress", adminEmailAddress) :
                new ObjectParameter("AdminEmailAddress", typeof(string));
    
            var adminUserIdParameter = adminUserId != null ?
                new ObjectParameter("AdminUserId", adminUserId) :
                new ObjectParameter("AdminUserId", typeof(string));
    
            var adminPasswordParameter = adminPassword != null ?
                new ObjectParameter("AdminPassword", adminPassword) :
                new ObjectParameter("AdminPassword", typeof(string));
    
            var adminProfilePhotoParameter = adminProfilePhoto != null ?
                new ObjectParameter("AdminProfilePhoto", adminProfilePhoto) :
                new ObjectParameter("AdminProfilePhoto", typeof(string));
    
            var createdDateParameter = createdDate.HasValue ?
                new ObjectParameter("CreatedDate", createdDate) :
                new ObjectParameter("CreatedDate", typeof(System.DateTime));
    
            var modifiedDateParameter = modifiedDate.HasValue ?
                new ObjectParameter("ModifiedDate", modifiedDate) :
                new ObjectParameter("ModifiedDate", typeof(System.DateTime));
    
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("IsActive", isActive) :
                new ObjectParameter("IsActive", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_SchoolAdmin", adminIdParameter, schoolIdParameter, adminFirstnameParameter, adminLastnameParameter, adminEmailAddressParameter, adminUserIdParameter, adminPasswordParameter, adminProfilePhotoParameter, createdDateParameter, modifiedDateParameter, isActiveParameter);
        }
    
        public virtual int usp_SchoolInfo(Nullable<System.Guid> schoolId, string schoolName, string schoolDescription, string schoolLogo, string schoolVideo, Nullable<System.DateTime> creationDate, Nullable<System.DateTime> modifiedDate, Nullable<bool> isActive)
        {
            var schoolIdParameter = schoolId.HasValue ?
                new ObjectParameter("SchoolId", schoolId) :
                new ObjectParameter("SchoolId", typeof(System.Guid));
    
            var schoolNameParameter = schoolName != null ?
                new ObjectParameter("SchoolName", schoolName) :
                new ObjectParameter("SchoolName", typeof(string));
    
            var schoolDescriptionParameter = schoolDescription != null ?
                new ObjectParameter("SchoolDescription", schoolDescription) :
                new ObjectParameter("SchoolDescription", typeof(string));
    
            var schoolLogoParameter = schoolLogo != null ?
                new ObjectParameter("SchoolLogo", schoolLogo) :
                new ObjectParameter("SchoolLogo", typeof(string));
    
            var schoolVideoParameter = schoolVideo != null ?
                new ObjectParameter("SchoolVideo", schoolVideo) :
                new ObjectParameter("SchoolVideo", typeof(string));
    
            var creationDateParameter = creationDate.HasValue ?
                new ObjectParameter("CreationDate", creationDate) :
                new ObjectParameter("CreationDate", typeof(System.DateTime));
    
            var modifiedDateParameter = modifiedDate.HasValue ?
                new ObjectParameter("modifiedDate", modifiedDate) :
                new ObjectParameter("modifiedDate", typeof(System.DateTime));
    
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("IsActive", isActive) :
                new ObjectParameter("IsActive", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_SchoolInfo", schoolIdParameter, schoolNameParameter, schoolDescriptionParameter, schoolLogoParameter, schoolVideoParameter, creationDateParameter, modifiedDateParameter, isActiveParameter);
        }
    
        public virtual int Sp_DC_SchoolInfo(Nullable<System.Guid> schoolId, string schoolName, string schoolDescription, string schoolLogo, string schoolVideo, string schoolThumbnail, Nullable<System.DateTime> creationDate, Nullable<System.DateTime> modifiedDate, Nullable<bool> isActive)
        {
            var schoolIdParameter = schoolId.HasValue ?
                new ObjectParameter("SchoolId", schoolId) :
                new ObjectParameter("SchoolId", typeof(System.Guid));
    
            var schoolNameParameter = schoolName != null ?
                new ObjectParameter("SchoolName", schoolName) :
                new ObjectParameter("SchoolName", typeof(string));
    
            var schoolDescriptionParameter = schoolDescription != null ?
                new ObjectParameter("SchoolDescription", schoolDescription) :
                new ObjectParameter("SchoolDescription", typeof(string));
    
            var schoolLogoParameter = schoolLogo != null ?
                new ObjectParameter("SchoolLogo", schoolLogo) :
                new ObjectParameter("SchoolLogo", typeof(string));
    
            var schoolVideoParameter = schoolVideo != null ?
                new ObjectParameter("SchoolVideo", schoolVideo) :
                new ObjectParameter("SchoolVideo", typeof(string));
    
            var schoolThumbnailParameter = schoolThumbnail != null ?
                new ObjectParameter("SchoolThumbnail", schoolThumbnail) :
                new ObjectParameter("SchoolThumbnail", typeof(string));
    
            var creationDateParameter = creationDate.HasValue ?
                new ObjectParameter("CreationDate", creationDate) :
                new ObjectParameter("CreationDate", typeof(System.DateTime));
    
            var modifiedDateParameter = modifiedDate.HasValue ?
                new ObjectParameter("modifiedDate", modifiedDate) :
                new ObjectParameter("modifiedDate", typeof(System.DateTime));
    
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("IsActive", isActive) :
                new ObjectParameter("IsActive", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_DC_SchoolInfo", schoolIdParameter, schoolNameParameter, schoolDescriptionParameter, schoolLogoParameter, schoolVideoParameter, schoolThumbnailParameter, creationDateParameter, modifiedDateParameter, isActiveParameter);
        }
    
        public virtual int SP_DC_SchoolUser(Nullable<System.Guid> userId, Nullable<System.Guid> schoolId, string userFirstname, string userLastname, string userEmailAddress, string userName, string userPassword, string userProfilePhoto, string userRole, string userPhoneNumber, Nullable<System.DateTime> createdDate, Nullable<System.DateTime> modifiedDate, Nullable<bool> isActive)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(System.Guid));
    
            var schoolIdParameter = schoolId.HasValue ?
                new ObjectParameter("SchoolId", schoolId) :
                new ObjectParameter("SchoolId", typeof(System.Guid));
    
            var userFirstnameParameter = userFirstname != null ?
                new ObjectParameter("UserFirstname", userFirstname) :
                new ObjectParameter("UserFirstname", typeof(string));
    
            var userLastnameParameter = userLastname != null ?
                new ObjectParameter("UserLastname", userLastname) :
                new ObjectParameter("UserLastname", typeof(string));
    
            var userEmailAddressParameter = userEmailAddress != null ?
                new ObjectParameter("UserEmailAddress", userEmailAddress) :
                new ObjectParameter("UserEmailAddress", typeof(string));
    
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            var userPasswordParameter = userPassword != null ?
                new ObjectParameter("UserPassword", userPassword) :
                new ObjectParameter("UserPassword", typeof(string));
    
            var userProfilePhotoParameter = userProfilePhoto != null ?
                new ObjectParameter("UserProfilePhoto", userProfilePhoto) :
                new ObjectParameter("UserProfilePhoto", typeof(string));
    
            var userRoleParameter = userRole != null ?
                new ObjectParameter("UserRole", userRole) :
                new ObjectParameter("UserRole", typeof(string));
    
            var userPhoneNumberParameter = userPhoneNumber != null ?
                new ObjectParameter("UserPhoneNumber", userPhoneNumber) :
                new ObjectParameter("UserPhoneNumber", typeof(string));
    
            var createdDateParameter = createdDate.HasValue ?
                new ObjectParameter("CreatedDate", createdDate) :
                new ObjectParameter("CreatedDate", typeof(System.DateTime));
    
            var modifiedDateParameter = modifiedDate.HasValue ?
                new ObjectParameter("ModifiedDate", modifiedDate) :
                new ObjectParameter("ModifiedDate", typeof(System.DateTime));
    
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("IsActive", isActive) :
                new ObjectParameter("IsActive", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DC_SchoolUser", userIdParameter, schoolIdParameter, userFirstnameParameter, userLastnameParameter, userEmailAddressParameter, userNameParameter, userPasswordParameter, userProfilePhotoParameter, userRoleParameter, userPhoneNumberParameter, createdDateParameter, modifiedDateParameter, isActiveParameter);
        }
    }
}
