//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigiChamps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DC_Notification
    {
        public long Id { get; set; }
        public Nullable<int> Regdno { get; set; }
        public Nullable<int> TypeId { get; set; }
        public string Type { get; set; }
        public string Notification { get; set; }
        public Nullable<bool> Is_Clicked { get; set; }
        public Nullable<System.DateTime> Inserted_Date { get; set; }
    }
}
