//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigiChamps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DC_Order_Pkg
    {
        public tbl_DC_Order_Pkg()
        {
            this.tbl_DC_Order_Pkg_Sub = new HashSet<tbl_DC_Order_Pkg_Sub>();
        }
    
        public int OrderPkg_ID { get; set; }
        public Nullable<int> Order_ID { get; set; }
        public string Order_No { get; set; }
        public Nullable<int> Package_ID { get; set; }
        public string Package_Name { get; set; }
        public string Package_Desc { get; set; }
        public Nullable<int> Total_Chapter { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Thumbnail { get; set; }
        public Nullable<int> Subscription_Period { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> Inserted_Date { get; set; }
        public Nullable<System.DateTime> Expiry_Date { get; set; }
        public string Inserted_By { get; set; }
        public string Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public Nullable<bool> Is_Active { get; set; }
        public Nullable<bool> Is_Deleted { get; set; }
        public Nullable<bool> Is_Offline { get; set; }
    
        public virtual tbl_DC_Order tbl_DC_Order { get; set; }
        public virtual ICollection<tbl_DC_Order_Pkg_Sub> tbl_DC_Order_Pkg_Sub { get; set; }
        public virtual tbl_DC_Package tbl_DC_Package { get; set; }
    }
}
