//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigiChamps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DC_Class_Section
    {
        public tbl_DC_Class_Section()
        {
            this.tbl_DC_School_AssingTeacher = new HashSet<tbl_DC_School_AssingTeacher>();
            this.tbl_DC_Shool_TimeTable = new HashSet<tbl_DC_Shool_TimeTable>();
            this.tbl_DC_School_Homework = new HashSet<tbl_DC_School_Homework>();
        }
    
        public System.Guid SectionId { get; set; }
        public Nullable<System.Guid> ClassId { get; set; }
        public string SectionName { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> Class_Id { get; set; }
        public Nullable<System.Guid> School_Id { get; set; }
    
        public virtual tbl_DC_School_Class tbl_DC_School_Class { get; set; }
        public virtual ICollection<tbl_DC_School_AssingTeacher> tbl_DC_School_AssingTeacher { get; set; }
        public virtual ICollection<tbl_DC_Shool_TimeTable> tbl_DC_Shool_TimeTable { get; set; }
        public virtual ICollection<tbl_DC_School_Homework> tbl_DC_School_Homework { get; set; }
    }
}
