//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigiChamps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DC_Question_Answer
    {
        public int Answer_ID { get; set; }
        public Nullable<int> Question_ID { get; set; }
        public string Option_Desc { get; set; }
        public string Option_Image { get; set; }
        public string Answer_desc { get; set; }
        public string Answer_Image { get; set; }
        public Nullable<bool> Is_Answer { get; set; }
        public string Inserted_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public string Modified_By { get; set; }
        public Nullable<bool> Is_Active { get; set; }
        public Nullable<bool> Is_Deleted { get; set; }
    }
}
