//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigiChamps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DC_USER_SECURITY
    {
        public string USER_CODE { get; set; }
        public string USER_NAME { get; set; }
        public string PASSWORD { get; set; }
        public Nullable<int> ROLE_TYPE { get; set; }
        public string ROLE_CODE { get; set; }
        public Nullable<bool> IS_ACCEPTED { get; set; }
        public string STATUS { get; set; }
    
        public virtual tbl_DC_Role tbl_DC_Role { get; set; }
    }
}
