//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigiChamps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DC_Ticket
    {
        public tbl_DC_Ticket()
        {
            this.tbl_DC_Ticket_Assign = new HashSet<tbl_DC_Ticket_Assign>();
            this.tbl_DC_Ticket_Thread = new HashSet<tbl_DC_Ticket_Thread>();
        }
    
        public int Ticket_ID { get; set; }
        public string Ticket_No { get; set; }
        public Nullable<int> Student_ID { get; set; }
        public Nullable<int> Board_ID { get; set; }
        public Nullable<int> Class_ID { get; set; }
        public Nullable<int> Subject_ID { get; set; }
        public Nullable<int> Chapter_ID { get; set; }
        public string Question { get; set; }
        public string Question_Image { get; set; }
        public string Status { get; set; }
        public Nullable<int> Inserted_By { get; set; }
        public Nullable<System.DateTime> Inserted_Date { get; set; }
        public Nullable<int> Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public Nullable<bool> Is_Active { get; set; }
        public Nullable<bool> Is_Deleted { get; set; }
        public string Remark { get; set; }
        public Nullable<int> Teach_ID { get; set; }
        public Nullable<System.DateTime> Assign_Date { get; set; }
    
        public virtual ICollection<tbl_DC_Ticket_Assign> tbl_DC_Ticket_Assign { get; set; }
        public virtual ICollection<tbl_DC_Ticket_Thread> tbl_DC_Ticket_Thread { get; set; }
    }
}
