//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigiChamps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DC_Attendance
    {
        public int Attendance_Id { get; set; }
        public Nullable<int> Teach_Id { get; set; }
        public Nullable<int> Class_Id { get; set; }
        public Nullable<int> Batch_Id { get; set; }
        public Nullable<int> Batch_Assign_Id { get; set; }
        public Nullable<int> Regd_Id { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public Nullable<bool> Is_Present { get; set; }
        public Nullable<bool> Is_Active { get; set; }
        public Nullable<bool> Is_Delete { get; set; }
        public Nullable<System.DateTime> Inserted_Date { get; set; }
        public string Inserted_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public string Modified_By { get; set; }
        public Nullable<System.DateTime> Attendance_Date { get; set; }
    }
}
