//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigiChamps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DC_Ticket_Dtl
    {
        public tbl_DC_Ticket_Dtl()
        {
            this.tbl_DC_Ticket_Thread = new HashSet<tbl_DC_Ticket_Thread>();
        }
    
        public int Ticket_Dtls_ID { get; set; }
        public Nullable<int> Ticket_ID { get; set; }
        public string Answer { get; set; }
        public string Answer_Image { get; set; }
        public Nullable<int> Replied_By { get; set; }
        public Nullable<System.DateTime> Replied_Date { get; set; }
        public Nullable<bool> Is_Active { get; set; }
        public Nullable<bool> Is_Deleted { get; set; }
    
        public virtual ICollection<tbl_DC_Ticket_Thread> tbl_DC_Ticket_Thread { get; set; }
    }
}
