//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigiChamps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DC_Menuitems
    {
        public tbl_DC_Menuitems()
        {
            this.tbl_DC_Menu_Permission = new HashSet<tbl_DC_Menu_Permission>();
        }
    
        public int Menu_Key_ID { get; set; }
        public string Menu_Parameter1 { get; set; }
        public string Menu_Parameter2 { get; set; }
        public string Menu_Parameter3 { get; set; }
        public string Inserted_By { get; set; }
        public Nullable<System.DateTime> Inserted_Date { get; set; }
        public string Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public Nullable<bool> Is_Active { get; set; }
        public Nullable<bool> Is_Deleted { get; set; }
    
        public virtual ICollection<tbl_DC_Menu_Permission> tbl_DC_Menu_Permission { get; set; }
    }
}
