//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigiChamps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DC_Shool_TimeTable
    {
        public System.Guid TimeTableId { get; set; }
        public System.Guid SchoolId { get; set; }
        public int Class_Id { get; set; }
        public Nullable<System.Guid> SectionId { get; set; }
        public Nullable<System.Guid> SubjectId { get; set; }
        public Nullable<System.Guid> PeriodId { get; set; }
        public string Day { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual tbl_DC_Class tbl_DC_Class { get; set; }
        public virtual tbl_DC_Class_Section tbl_DC_Class_Section { get; set; }
        public virtual tbl_DC_Period tbl_DC_Period { get; set; }
        public virtual tbl_DC_School_Info tbl_DC_School_Info { get; set; }
        public virtual tbl_DC_School_Subject tbl_DC_School_Subject { get; set; }
        public virtual tbl_DC_Shool_TimeTable tbl_DC_Shool_TimeTable1 { get; set; }
        public virtual tbl_DC_Shool_TimeTable tbl_DC_Shool_TimeTable2 { get; set; }
    }
}
