//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigiChamps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DC_Registration
    {
        public tbl_DC_Registration()
        {
            this.tbl_DC_Cart = new HashSet<tbl_DC_Cart>();
            this.tbl_DC_Feedback_Chapter = new HashSet<tbl_DC_Feedback_Chapter>();
            this.tbl_DC_Feedback_Teacher = new HashSet<tbl_DC_Feedback_Teacher>();
            this.tbl_DC_Order = new HashSet<tbl_DC_Order>();
            this.tbl_DC_Pre_book = new HashSet<tbl_DC_Pre_book>();
            this.tbl_DC_Registration_Dtl = new HashSet<tbl_DC_Registration_Dtl>();
            this.tbl_DC_Student_Batch_Assign = new HashSet<tbl_DC_Student_Batch_Assign>();
            this.tbl_DC_Ticket_Assign = new HashSet<tbl_DC_Ticket_Assign>();
        }
    
        public int Regd_ID { get; set; }
        public string Regd_No { get; set; }
        public string Customer_Name { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<bool> Gender { get; set; }
        public string Phone { get; set; }
        public string Organisation_Name { get; set; }
        public string Pincode { get; set; }
        public string Address { get; set; }
        public string Image { get; set; }
        public Nullable<bool> Is_prebook { get; set; }
        public Nullable<System.DateTime> Inserted_Date { get; set; }
        public string Inserted_By { get; set; }
        public string Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public Nullable<bool> Is_Active { get; set; }
        public Nullable<bool> Is_Deleted { get; set; }
        public Nullable<int> Parent_Id { get; set; }
        public string Praent_Name { get; set; }
        public string Parent_Mail { get; set; }
        public string Parent_Mobile { get; set; }
        public string P_Relation { get; set; }
        public string Device_id { get; set; }
        public Nullable<System.Guid> SchoolId { get; set; }
    
        public virtual ICollection<tbl_DC_Cart> tbl_DC_Cart { get; set; }
        public virtual ICollection<tbl_DC_Feedback_Chapter> tbl_DC_Feedback_Chapter { get; set; }
        public virtual ICollection<tbl_DC_Feedback_Teacher> tbl_DC_Feedback_Teacher { get; set; }
        public virtual ICollection<tbl_DC_Order> tbl_DC_Order { get; set; }
        public virtual ICollection<tbl_DC_Pre_book> tbl_DC_Pre_book { get; set; }
        public virtual ICollection<tbl_DC_Registration_Dtl> tbl_DC_Registration_Dtl { get; set; }
        public virtual ICollection<tbl_DC_Student_Batch_Assign> tbl_DC_Student_Batch_Assign { get; set; }
        public virtual ICollection<tbl_DC_Ticket_Assign> tbl_DC_Ticket_Assign { get; set; }
        public virtual tbl_DC_School_Info tbl_DC_School_Info { get; set; }
    }
}
