//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigiChamps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DC_Board
    {
        public tbl_DC_Board()
        {
            this.tbl_DC_Cart_Dtl = new HashSet<tbl_DC_Cart_Dtl>();
            this.tbl_DC_Class = new HashSet<tbl_DC_Class>();
            this.tbl_DC_Course_Teacher_Assign = new HashSet<tbl_DC_Course_Teacher_Assign>();
            this.tbl_DC_Exam = new HashSet<tbl_DC_Exam>();
            this.tbl_DC_Module = new HashSet<tbl_DC_Module>();
            this.tbl_DC_Order_Pkg_Sub = new HashSet<tbl_DC_Order_Pkg_Sub>();
            this.tbl_DC_Question = new HashSet<tbl_DC_Question>();
            this.tbl_DC_Registration_Dtl = new HashSet<tbl_DC_Registration_Dtl>();
            this.tbl_DC_Topic = new HashSet<tbl_DC_Topic>();
        }
    
        public int Board_Id { get; set; }
        public string Board_Name { get; set; }
        public Nullable<System.DateTime> Inserted_Date { get; set; }
        public Nullable<int> Inserted_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public Nullable<int> Modified_By { get; set; }
        public Nullable<bool> Is_Active { get; set; }
        public Nullable<bool> Is_Deleted { get; set; }
    
        public virtual ICollection<tbl_DC_Cart_Dtl> tbl_DC_Cart_Dtl { get; set; }
        public virtual ICollection<tbl_DC_Class> tbl_DC_Class { get; set; }
        public virtual ICollection<tbl_DC_Course_Teacher_Assign> tbl_DC_Course_Teacher_Assign { get; set; }
        public virtual ICollection<tbl_DC_Exam> tbl_DC_Exam { get; set; }
        public virtual ICollection<tbl_DC_Module> tbl_DC_Module { get; set; }
        public virtual ICollection<tbl_DC_Order_Pkg_Sub> tbl_DC_Order_Pkg_Sub { get; set; }
        public virtual ICollection<tbl_DC_Question> tbl_DC_Question { get; set; }
        public virtual ICollection<tbl_DC_Registration_Dtl> tbl_DC_Registration_Dtl { get; set; }
        public virtual ICollection<tbl_DC_Topic> tbl_DC_Topic { get; set; }
    }
}
