//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigiChamps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DC_CouponCode
    {
        public int Code_Id { get; set; }
        public Nullable<int> Coupon_Type { get; set; }
        public string Coupon_Code { get; set; }
        public Nullable<decimal> Discount_Price { get; set; }
        public Nullable<decimal> Discount_Percent { get; set; }
        public Nullable<System.DateTime> Valid_From { get; set; }
        public Nullable<System.DateTime> Valid_To { get; set; }
        public Nullable<decimal> Pricerange_From { get; set; }
        public Nullable<decimal> Pricertange_To { get; set; }
        public Nullable<bool> Is_Default { get; set; }
        public string Inserted_By { get; set; }
        public Nullable<System.DateTime> Inserted_Date { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public Nullable<bool> Is_Active { get; set; }
        public Nullable<bool> Is_Delete { get; set; }
    }
}
