//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigiChamps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DC_Ticket_Assign
    {
        public int AssignTicket_ID { get; set; }
        public Nullable<int> Ticket_ID { get; set; }
        public string Ticket_No { get; set; }
        public Nullable<int> Student_ID { get; set; }
        public Nullable<int> Teach_ID { get; set; }
        public Nullable<System.DateTime> Assign_Date { get; set; }
        public Nullable<bool> Is_Close { get; set; }
        public Nullable<System.DateTime> Close_Date { get; set; }
        public string Remark { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> Inserted_By { get; set; }
        public Nullable<System.DateTime> Inserted_Date { get; set; }
        public Nullable<int> Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public Nullable<bool> Is_Active { get; set; }
        public Nullable<bool> Is_Deleted { get; set; }
    
        public virtual tbl_DC_Registration tbl_DC_Registration { get; set; }
        public virtual tbl_DC_Teacher tbl_DC_Teacher { get; set; }
        public virtual tbl_DC_Ticket tbl_DC_Ticket { get; set; }
    }
}
