//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigiChamps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DC_Order_Pkg_Sub_Mod
    {
        public int OrderPkgSubMod_ID { get; set; }
        public Nullable<int> OrderPkgSub_ID { get; set; }
        public Nullable<int> Chapter_ID { get; set; }
        public string Chapter_Name { get; set; }
        public Nullable<int> Module_ID { get; set; }
        public string Module_Name { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> Inserted_Date { get; set; }
        public string Inserted_By { get; set; }
        public string Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public Nullable<bool> Is_Active { get; set; }
        public Nullable<bool> Is_Deleted { get; set; }
    
        public virtual tbl_DC_Chapter tbl_DC_Chapter { get; set; }
        public virtual tbl_DC_Module tbl_DC_Module { get; set; }
        public virtual tbl_DC_Order_Pkg_Sub tbl_DC_Order_Pkg_Sub { get; set; }
    }
}
