//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigiChamps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DC_Batch
    {
        public int Batch_Id { get; set; }
        public Nullable<int> Class_Id { get; set; }
        public Nullable<int> Board_Id { get; set; }
        public Nullable<int> Subject_Id { get; set; }
        public Nullable<int> Centre_Id { get; set; }
        public string Batch_Name { get; set; }
        public string Batch_From_Time { get; set; }
        public string Batch_To_Time { get; set; }
        public string Batch_Days { get; set; }
        public string Batch_Code { get; set; }
        public Nullable<System.DateTime> Inserted_Date { get; set; }
        public string Inserted_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public string Modified_By { get; set; }
        public Nullable<bool> Is_Active { get; set; }
        public Nullable<bool> Is_Deleted { get; set; }
    
        public virtual tbl_DC_Centre tbl_DC_Centre { get; set; }
    }
}
