//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigiChamps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DC_Menu_Permission
    {
        public int Permission_ID { get; set; }
        public Nullable<int> ROLE_ID { get; set; }
        public Nullable<int> Role_Type_ID { get; set; }
        public Nullable<int> Menu_Key_ID { get; set; }
        public string Inserted_By { get; set; }
        public Nullable<System.DateTime> Inserted_Date { get; set; }
        public string Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public Nullable<bool> Is_Active { get; set; }
        public Nullable<bool> Is_Deleted { get; set; }
    
        public virtual tbl_DC_Menuitems tbl_DC_Menuitems { get; set; }
        public virtual tbl_DC_Role tbl_DC_Role { get; set; }
        public virtual tbl_DC_Role_Type tbl_DC_Role_Type { get; set; }
    }
}
