//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigiChamps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DC_Order
    {
        public tbl_DC_Order()
        {
            this.tbl_DC_Order_Pkg = new HashSet<tbl_DC_Order_Pkg>();
            this.tbl_DC_Order_Tax = new HashSet<tbl_DC_Order_Tax>();
        }
    
        public int Order_ID { get; set; }
        public string Order_No { get; set; }
        public string Cart_Order_No { get; set; }
        public string Trans_No { get; set; }
        public Nullable<int> Regd_ID { get; set; }
        public string Regd_No { get; set; }
        public Nullable<int> No_of_Package { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> Disc_Perc { get; set; }
        public Nullable<decimal> Disc_Amt { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string Amt_In_Words { get; set; }
        public string Payment_Mode { get; set; }
        public Nullable<bool> Is_Paid { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> Inserted_Date { get; set; }
        public string Inserted_By { get; set; }
        public string Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public Nullable<bool> Is_Active { get; set; }
        public Nullable<bool> Is_Deleted { get; set; }
    
        public virtual ICollection<tbl_DC_Order_Pkg> tbl_DC_Order_Pkg { get; set; }
        public virtual ICollection<tbl_DC_Order_Tax> tbl_DC_Order_Tax { get; set; }
        public virtual tbl_DC_Registration tbl_DC_Registration { get; set; }
    }
}
