//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigiChamps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DC_Sms_API
    {
        public tbl_DC_Sms_API()
        {
            this.tbl_DC_Sms_Template = new HashSet<tbl_DC_Sms_Template>();
        }
    
        public int Api_Id { get; set; }
        public string Api_Name { get; set; }
        public string Api_Url { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Sender_Type { get; set; }
        public string Message_Type { get; set; }
        public Nullable<System.DateTime> Inserted_Date { get; set; }
        public string Inserted_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public string Modified_By { get; set; }
        public Nullable<bool> Is_Active { get; set; }
        public Nullable<bool> Is_Deleted { get; set; }
    
        public virtual ICollection<tbl_DC_Sms_Template> tbl_DC_Sms_Template { get; set; }
    }
}
