//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigiChamps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DC_Tablet_Purchase
    {
        public tbl_DC_Tablet_Purchase()
        {
            this.tbl_DC_Package = new HashSet<tbl_DC_Package>();
        }
    
        public int Tablet_Id { get; set; }
        public string Tablet_Name { get; set; }
        public string Tablet_Description { get; set; }
        public Nullable<decimal> Tablet_Price { get; set; }
        public Nullable<decimal> Discount_Amount { get; set; }
        public Nullable<int> Subscription_Period { get; set; }
        public string Other_Details { get; set; }
        public string Inserted_By { get; set; }
        public Nullable<System.DateTime> Inserted_Date { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public Nullable<bool> Is_Active { get; set; }
        public Nullable<bool> Is_Deleted { get; set; }
    
        public virtual ICollection<tbl_DC_Package> tbl_DC_Package { get; set; }
    }
}
