//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigiChamps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DC_Order_Tax
    {
        public int Tax_Order_ID { get; set; }
        public int Order_ID { get; set; }
        public string Order_No { get; set; }
        public Nullable<int> Tax_ID { get; set; }
        public Nullable<int> Tax_Type_ID { get; set; }
        public Nullable<System.DateTime> Tax_Effect_Date { get; set; }
        public Nullable<decimal> Tax_Amt { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> Inserted_Date { get; set; }
        public string Inserted_By { get; set; }
        public string Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public Nullable<bool> Is_Active { get; set; }
        public Nullable<bool> Is_Deleted { get; set; }
    
        public virtual tbl_DC_Order tbl_DC_Order { get; set; }
        public virtual tbl_DC_Tax_Master tbl_DC_Tax_Master { get; set; }
        public virtual tbl_DC_Tax_Type_Master tbl_DC_Tax_Type_Master { get; set; }
    }
}
