//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigiChamps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DC_School_ExamType
    {
        public tbl_DC_School_ExamType()
        {
            this.tbl_DC_School_ExamSchedule = new HashSet<tbl_DC_School_ExamSchedule>();
        }
    
        public System.Guid ExamTypeId { get; set; }
        public Nullable<System.Guid> SchoolId { get; set; }
        public string ExamTypeName { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual ICollection<tbl_DC_School_ExamSchedule> tbl_DC_School_ExamSchedule { get; set; }
        public virtual tbl_DC_School_Info tbl_DC_School_Info { get; set; }
    }
}
