//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigiChamps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DC_Pre_book
    {
        public int Book_Id { get; set; }
        public Nullable<int> Regd_Id { get; set; }
        public string Ref_No { get; set; }
        public string Reffered_from { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string School_Name { get; set; }
        public string Class { get; set; }
        public Nullable<bool> Ord_Status { get; set; }
        public Nullable<int> Order_Id { get; set; }
        public Nullable<System.DateTime> Inserted_Date { get; set; }
        public string Inserted_By { get; set; }
        public Nullable<bool> Is_Active { get; set; }
        public Nullable<bool> Is_Deleted { get; set; }
    
        public virtual tbl_DC_Registration tbl_DC_Registration { get; set; }
        public virtual tbl_DC_Pre_book tbl_DC_Pre_book1 { get; set; }
        public virtual tbl_DC_Pre_book tbl_DC_Pre_book2 { get; set; }
    }
}
