//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigiChamps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DC_Package
    {
        public tbl_DC_Package()
        {
            this.tbl_DC_Cart = new HashSet<tbl_DC_Cart>();
            this.tbl_DC_Cart_Dtl = new HashSet<tbl_DC_Cart_Dtl>();
            this.tbl_DC_Order_Pkg = new HashSet<tbl_DC_Order_Pkg>();
        }
    
        public int Package_ID { get; set; }
        public string Package_Name { get; set; }
        public string Package_Desc { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> Total_Chapter { get; set; }
        public string Thumbnail { get; set; }
        public Nullable<int> Subscripttion_Period { get; set; }
        public string Inserted_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public string Modified_By { get; set; }
        public Nullable<bool> Is_Active { get; set; }
        public Nullable<bool> Is_Deleted { get; set; }
        public Nullable<System.DateTime> Inserted_Date { get; set; }
        public Nullable<bool> Is_Offline { get; set; }
        public Nullable<int> Tablet_Id { get; set; }
    
        public virtual ICollection<tbl_DC_Cart> tbl_DC_Cart { get; set; }
        public virtual ICollection<tbl_DC_Cart_Dtl> tbl_DC_Cart_Dtl { get; set; }
        public virtual ICollection<tbl_DC_Order_Pkg> tbl_DC_Order_Pkg { get; set; }
        public virtual tbl_DC_Tablet_Purchase tbl_DC_Tablet_Purchase { get; set; }
    }
}
