//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigiChamps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DC_Module
    {
        public tbl_DC_Module()
        {
            this.tbl_DC_Order_Pkg_Sub_Mod = new HashSet<tbl_DC_Order_Pkg_Sub_Mod>();
        }
    
        public int Module_ID { get; set; }
        public Nullable<int> Board_Id { get; set; }
        public Nullable<int> Class_Id { get; set; }
        public Nullable<int> Subject_Id { get; set; }
        public Nullable<int> Chapter_Id { get; set; }
        public string Module_Name { get; set; }
        public string Module_Content_Name { get; set; }
        public string Module_Desc { get; set; }
        public string Module_Content { get; set; }
        public string Module_video { get; set; }
        public string Module_Image { get; set; }
        public Nullable<int> No_Of_Question { get; set; }
        public Nullable<bool> Is_Free { get; set; }
        public Nullable<int> Validity { get; set; }
        public string Question_PDF { get; set; }
        public string Question_PDF_Name { get; set; }
        public Nullable<bool> Is_Free_Test { get; set; }
        public string Inserted_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public string Modified_By { get; set; }
        public Nullable<bool> Is_Active { get; set; }
        public Nullable<bool> Is_Deleted { get; set; }
    
        public virtual tbl_DC_Board tbl_DC_Board { get; set; }
        public virtual tbl_DC_Chapter tbl_DC_Chapter { get; set; }
        public virtual tbl_DC_Class tbl_DC_Class { get; set; }
        public virtual tbl_DC_Subject tbl_DC_Subject { get; set; }
        public virtual ICollection<tbl_DC_Order_Pkg_Sub_Mod> tbl_DC_Order_Pkg_Sub_Mod { get; set; }
    }
}
