//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigiChamps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DC_Bank_Details
    {
        public int Cheque_ID { get; set; }
        public Nullable<int> Order_ID { get; set; }
        public string Bank_Name { get; set; }
        public string Branch_Name { get; set; }
        public string Bank_Address { get; set; }
        public string Cheque_No { get; set; }
        public Nullable<System.DateTime> Cheque_Date { get; set; }
        public string Inserted_By { get; set; }
        public Nullable<System.DateTime> Inserted_Date { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public Nullable<bool> Is_Active { get; set; }
        public Nullable<bool> Is_Delete { get; set; }
    }
}
