//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigiChamps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DC_Test_Assign
    {
        public int Retest_ID { get; set; }
        public Nullable<int> Regd_ID { get; set; }
        public Nullable<int> Topic_ID { get; set; }
        public Nullable<int> No_Of_Ques { get; set; }
        public Nullable<int> Exam_ID { get; set; }
        public Nullable<int> Power_ID { get; set; }
        public Nullable<int> No_Of_PowerQues { get; set; }
        public Nullable<bool> Is_Active { get; set; }
        public Nullable<bool> Is_Deleted { get; set; }
        public Nullable<System.DateTime> Inserted_Date { get; set; }
        public string Inserted_By { get; set; }
        public string Modified_By { get; set; }
    }
}
