//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigiChamps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DC_Teacher
    {
        public tbl_DC_Teacher()
        {
            this.tbl_DC_Course_Teacher_Assign = new HashSet<tbl_DC_Course_Teacher_Assign>();
            this.tbl_DC_Feedback_Teacher = new HashSet<tbl_DC_Feedback_Teacher>();
            this.tbl_DC_Ticket_Assign = new HashSet<tbl_DC_Ticket_Assign>();
        }
    
        public int Teach_ID { get; set; }
        public string Teacher_Name { get; set; }
        public string Designation { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Gender { get; set; }
        public string Email_ID { get; set; }
        public string Mobile { get; set; }
        public string Address { get; set; }
        public string Image { get; set; }
        public Nullable<int> TotalRaters { get; set; }
        public Nullable<decimal> AverageRating { get; set; }
        public Nullable<System.DateTime> Inserted_Date { get; set; }
        public string Inserted_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public string Modified_By { get; set; }
        public Nullable<bool> Is_Active { get; set; }
        public Nullable<bool> Is_Deleted { get; set; }
    
        public virtual ICollection<tbl_DC_Course_Teacher_Assign> tbl_DC_Course_Teacher_Assign { get; set; }
        public virtual ICollection<tbl_DC_Feedback_Teacher> tbl_DC_Feedback_Teacher { get; set; }
        public virtual ICollection<tbl_DC_Ticket_Assign> tbl_DC_Ticket_Assign { get; set; }
    }
}
