//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigiChamps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DC_Smtp_Details
    {
        public tbl_DC_Smtp_Details()
        {
            this.tbl_DC_MailConfigBody = new HashSet<tbl_DC_MailConfigBody>();
        }
    
        public int SMTP_ID { get; set; }
        public string SMTP_Email { get; set; }
        public string SMTP_Sender { get; set; }
        public string SMTP_HostName { get; set; }
        public string SMTP_User { get; set; }
        public string SMTP_Pwd { get; set; }
        public Nullable<int> SMTP_Port { get; set; }
        public Nullable<System.DateTime> Inserted_Date { get; set; }
        public string Inserted_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public string Modified_By { get; set; }
        public Nullable<bool> Is_Active { get; set; }
        public Nullable<bool> Is_Deleted { get; set; }
        public Nullable<bool> SMTP_Ssl { get; set; }
    
        public virtual ICollection<tbl_DC_MailConfigBody> tbl_DC_MailConfigBody { get; set; }
    }
}
