//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigiChamps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DC_Package_Period
    {
        public int Package_Period_Id { get; set; }
        public Nullable<int> Package_ID { get; set; }
        public Nullable<System.DateTime> Package_From { get; set; }
        public Nullable<System.DateTime> Package_To { get; set; }
        public Nullable<decimal> Included_Price { get; set; }
        public Nullable<decimal> Excluded_Price { get; set; }
        public Nullable<bool> Is_Active { get; set; }
        public Nullable<bool> Is_Deleted { get; set; }
        public string Inserted_By { get; set; }
        public Nullable<System.DateTime> Inserted_Date { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public string Modified_By { get; set; }
        public string Package_Type { get; set; }
    }
}
