//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigiChamps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DC_LoginStatus
    {
        public long id { get; set; }
        public string Login_ID { get; set; }
        public Nullable<System.DateTime> Login_DateTime { get; set; }
        public Nullable<System.DateTime> Logout_DateTime { get; set; }
        public string Login_IPAddress { get; set; }
        public string Login_By { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<bool> Is_Android { get; set; }
    }
}
