//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigiChamps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DC_MailConfigBody
    {
        public int EmailConf_ID { get; set; }
        public Nullable<int> SMTP_ID { get; set; }
        public Nullable<int> EmailConf_AlertName { get; set; }
        public string Email_Subject { get; set; }
        public string EmailConf_Body { get; set; }
        public string EmailConf_Alert { get; set; }
        public Nullable<System.DateTime> Inserted_Date { get; set; }
        public string Inserted_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public string Modified_By { get; set; }
        public Nullable<bool> Is_Active { get; set; }
        public Nullable<bool> Is_Deleted { get; set; }
    
        public virtual tbl_DC_Smtp_Details tbl_DC_Smtp_Details { get; set; }
    }
}
