//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigiChamps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DC_Student_Batch_Assign
    {
        public long Id { get; set; }
        public Nullable<int> Batch_Assign_Id { get; set; }
        public Nullable<int> Regd_Id { get; set; }
        public Nullable<System.DateTime> Inserted_Date { get; set; }
        public string Inserted_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public Nullable<bool> Is_Active { get; set; }
        public Nullable<bool> Is_Deleted { get; set; }
    
        public virtual tbl_DC_Batch_Assign tbl_DC_Batch_Assign { get; set; }
        public virtual tbl_DC_Registration tbl_DC_Registration { get; set; }
    }
}
