//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigiChamps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DC_Feedback
    {
        public int id { get; set; }
        public Nullable<int> Regd_Id { get; set; }
        public string Usercode { get; set; }
        public string Remark { get; set; }
        public Nullable<decimal> Rating { get; set; }
        public Nullable<System.DateTime> Inserted_Date { get; set; }
        public string Inserted_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public string Modified_By { get; set; }
        public Nullable<bool> Is_Active { get; set; }
        public Nullable<bool> Is_Deleted { get; set; }
        public string PhoneNo { get; set; }
        public string Class { get; set; }
        public string Category { get; set; }
        public string Message { get; set; }
        public string Name { get; set; }
    }
}
