//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigiChamps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DC_Percentage
    {
        public int ID { get; set; }
        public Nullable<int> Start_P { get; set; }
        public Nullable<int> END_P { get; set; }
        public Nullable<int> Inserted_by { get; set; }
        public Nullable<System.DateTime> Inserted_date { get; set; }
        public Nullable<int> Modify_by { get; set; }
        public Nullable<System.DateTime> Modified_date { get; set; }
        public Nullable<bool> Is_Active { get; set; }
        public Nullable<bool> Is_Deleted { get; set; }
    }
}
