//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigiChamps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DC_Career
    {
        public int Career_ID { get; set; }
        public string career_Name { get; set; }
        public Nullable<int> No_of_vacancy { get; set; }
        public string Experience { get; set; }
        public string Location { get; set; }
        public string Qualification { get; set; }
        public Nullable<System.DateTime> Opening_Date { get; set; }
        public Nullable<System.DateTime> Close_Date { get; set; }
        public string Walk_in_Time { get; set; }
        public string Phone { get; set; }
        public string Job_Description { get; set; }
        public string Inserted_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public string Modified_By { get; set; }
        public Nullable<bool> Is_Active { get; set; }
        public Nullable<bool> Is_Deleted { get; set; }
    }
}
