//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigiChamps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DC_Power_Question
    {
        public tbl_DC_Power_Question()
        {
            this.tbl_DC_Exam_Power = new HashSet<tbl_DC_Exam_Power>();
            this.tbl_DC_Question = new HashSet<tbl_DC_Question>();
        }
    
        public int Power_Id { get; set; }
        public string Power_Type { get; set; }
        public Nullable<System.DateTime> Inserted_Date { get; set; }
        public string Inserted_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public string Modified_By { get; set; }
        public Nullable<bool> Is_Active { get; set; }
        public Nullable<bool> Is_Deleted { get; set; }
    
        public virtual ICollection<tbl_DC_Exam_Power> tbl_DC_Exam_Power { get; set; }
        public virtual ICollection<tbl_DC_Question> tbl_DC_Question { get; set; }
    }
}
