//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigiChamps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DC_Feedback_Chapter
    {
        public int id { get; set; }
        public Nullable<int> Regd_Id { get; set; }
        public string Usercode { get; set; }
        public Nullable<int> Chapter_Id { get; set; }
        public Nullable<decimal> Ch_Rating { get; set; }
    
        public virtual tbl_DC_Chapter tbl_DC_Chapter { get; set; }
        public virtual tbl_DC_Registration tbl_DC_Registration { get; set; }
    }
}
