//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigiChamps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_DC_Teacher_Shift
    {
        public string Shift_Name { get; set; }
        public string Shift_From_Time { get; set; }
        public string Shift_To_Time { get; set; }
        public string Teacher_Name { get; set; }
        public int Shift_teach_ID { get; set; }
        public string Shift_Days { get; set; }
        public Nullable<System.DateTime> Efective_Date { get; set; }
    }
}
