//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigiChamps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_DC_SMS_API
    {
        public string Api_Name { get; set; }
        public int Api_Id { get; set; }
        public string Api_Url { get; set; }
        public string Message_Type { get; set; }
        public int Sms_Id { get; set; }
        public string Sms_Alert_Name { get; set; }
        public string Sms_Body { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Sender_Type { get; set; }
    }
}
