//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigiChamps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_DC_Package
    {
        public string Package_Name { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> Subscripttion_Period { get; set; }
        public int PackageDtl_ID { get; set; }
        public Nullable<int> Class_Id { get; set; }
        public int Package_ID { get; set; }
        public Nullable<System.DateTime> Inserted_Date { get; set; }
    }
}
