//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigiChamps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_DC_Tickets_and_Teacher
    {
        public string Teacher_Name { get; set; }
        public string Board_Name { get; set; }
        public Nullable<int> Board_ID { get; set; }
        public Nullable<int> Class_ID { get; set; }
        public string Class_Name { get; set; }
        public Nullable<int> Subject_ID { get; set; }
        public string Subject { get; set; }
        public string Chapter { get; set; }
        public int Chapter_Id { get; set; }
        public string Question { get; set; }
        public string Question_Image { get; set; }
        public string Status { get; set; }
        public int Regd_ID { get; set; }
        public string Customer_Name { get; set; }
        public int Ticket_ID { get; set; }
        public string Remark { get; set; }
        public string Ticket_No { get; set; }
        public Nullable<int> Student_ID { get; set; }
        public Nullable<int> Teach_ID { get; set; }
        public Nullable<System.DateTime> Inserted_Date { get; set; }
        public Nullable<int> Ticket_Dtls_ID { get; set; }
        public Nullable<int> TOTALTKT { get; set; }
        public Nullable<int> OPENTKT { get; set; }
        public Nullable<int> CLOSETKT { get; set; }
    }
}
