//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigiChamps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_DC_Student_details
    {
        public int Regd_ID { get; set; }
        public string Regd_No { get; set; }
        public string Board_Name { get; set; }
        public string Class_Name { get; set; }
        public string Customer_Name { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
    }
}
