//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigiChamps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_All_Student_Details
    {
        public int Regd_ID { get; set; }
        public string Regd_No { get; set; }
        public string Customer_Name { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string Board_Name { get; set; }
        public string Class_Name { get; set; }
        public Nullable<int> Board_Id { get; set; }
        public Nullable<int> Class_ID { get; set; }
        public string STATUS { get; set; }
        public string Phone { get; set; }
        public string Organisation_Name { get; set; }
        public string Pincode { get; set; }
        public string Address { get; set; }
        public string Image { get; set; }
        public Nullable<int> Secure_Id { get; set; }
        public string Answer { get; set; }
        public Nullable<System.DateTime> Inserted_Date { get; set; }
        public string Praent_Name { get; set; }
        public Nullable<int> Parent_Id { get; set; }
        public string Parent_Mail { get; set; }
        public string Parent_Mobile { get; set; }
        public string P_Relation { get; set; }
        public Nullable<bool> IS_ACCEPTED { get; set; }
    }
}
