//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigiChamps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_DC_CourseAssign
    {
        public string Teacher_Name { get; set; }
        public string Board_Name { get; set; }
        public string Class_Name { get; set; }
        public int CourseAssn_ID { get; set; }
        public string Subject { get; set; }
        public Nullable<int> Teacher_ID { get; set; }
    }
}
