//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigiChamps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_DC_Attendance_Batch_Details
    {
        public int Batch_Id { get; set; }
        public int Batch_Assign_Id { get; set; }
        public Nullable<int> Teach_ID { get; set; }
        public string Batch_Name { get; set; }
        public string Batch_Code { get; set; }
    }
}
