//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigiChamps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_DC_Package_Learn
    {
        public int Order_ID { get; set; }
        public string Order_No { get; set; }
        public string Cart_Order_No { get; set; }
        public string Trans_No { get; set; }
        public Nullable<System.DateTime> Expiry_Date { get; set; }
        public Nullable<int> Regd_ID { get; set; }
        public string Regd_No { get; set; }
        public Nullable<int> No_of_Package { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> Disc_Perc { get; set; }
        public Nullable<decimal> Disc_Amt { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string Amt_In_Words { get; set; }
        public string Payment_Mode { get; set; }
        public Nullable<bool> Is_Paid { get; set; }
        public int OrderPkg_ID { get; set; }
        public Nullable<int> Package_ID { get; set; }
        public string Package_Name { get; set; }
        public string Package_Desc { get; set; }
        public Nullable<int> Total_Chapter { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Thumbnail { get; set; }
        public Nullable<int> Subscription_Period { get; set; }
        public int OrderPkgSub_ID { get; set; }
        public Nullable<int> Board_ID { get; set; }
        public string Board_Name { get; set; }
        public Nullable<int> Class_ID { get; set; }
        public string Class_Name { get; set; }
        public Nullable<int> Subject_ID { get; set; }
        public string Subject_Name { get; set; }
        public Nullable<int> Chapter_ID { get; set; }
        public string Chapter_Name { get; set; }
        public Nullable<System.DateTime> Inserted_Date { get; set; }
        public Nullable<bool> Is_Offline { get; set; }
    }
}
