//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigiChamps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_DC_Assign_Batch
    {
        public int Regd_ID { get; set; }
        public string Customer_Name { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public Nullable<int> Class_ID { get; set; }
        public string Class_Name { get; set; }
        public Nullable<int> Subject_ID { get; set; }
        public Nullable<int> Batch_Assign_Id { get; set; }
        public Nullable<long> stu_batch_id { get; set; }
        public Nullable<int> Batch_Id { get; set; }
    }
}
