//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigiChamps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_DC_Package_Learn_Module
    {
        public int OrderPkgSubMod_ID { get; set; }
        public Nullable<int> OrderPkgSub_ID { get; set; }
        public Nullable<int> Chapter_ID { get; set; }
        public string Chapter_Name { get; set; }
        public Nullable<int> Module_ID { get; set; }
        public string Module_Name { get; set; }
        public string Module_Desc { get; set; }
        public string Module_Content { get; set; }
        public string Module_video { get; set; }
        public Nullable<bool> Is_Free { get; set; }
    }
}
