//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigiChamps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_DC_Role
    {
        public int ROLE_ID { get; set; }
        public string ROLE_CODE { get; set; }
        public string ROLE_TYPE { get; set; }
        public Nullable<System.DateTime> INSERTED_DATE { get; set; }
        public string INSERTED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<bool> IS_ACTIVE { get; set; }
        public Nullable<bool> IS_DELTED { get; set; }
    }
}
