//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigiChamps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_Offline_Student_Orders
    {
        public int Order_ID { get; set; }
        public string Order_No { get; set; }
        public string Cart_Order_No { get; set; }
        public string Trans_No { get; set; }
        public Nullable<int> Regd_ID { get; set; }
        public string Customer_Name { get; set; }
        public string Mobile { get; set; }
        public string Regd_No { get; set; }
        public Nullable<int> No_of_Package { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> Disc_Perc { get; set; }
        public Nullable<decimal> Disc_Amt { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string Amt_In_Words { get; set; }
        public string Payment_Mode { get; set; }
    }
}
