//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigiChamps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_Prebook_Students
    {
        public int Book_Id { get; set; }
        public string Ref_No { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<bool> Ord_Status { get; set; }
        public Nullable<int> Order_Id { get; set; }
        public string Customer_Name { get; set; }
        public string Regd_No { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public string Pincode { get; set; }
        public string Image { get; set; }
        public Nullable<System.DateTime> Inserted_Date { get; set; }
        public string School_Name { get; set; }
        public string Class { get; set; }
        public string Reffered_from { get; set; }
        public Nullable<bool> Is_Active { get; set; }
        public Nullable<bool> Is_Deleted { get; set; }
        public Nullable<bool> Is_prebook { get; set; }
    }
}
